# Generated by Django 5.1.3 on 2024-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi_paid_on_time',
            field=models.IntegerField(default=0),
        ),
    ]
